#!/bin/sh
# Include web-dev related files for formatting.
FILES=$(git diff --cached --name-only --diff-filter=ACMR \
  "*.js" "*.jsx" "*.ts" "*.tsx" "*.scss" "*.css" "*.py" "*.json" "*.html" | sed 's| |\\ |g')

[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs prettier --write --tab-width 2

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
