#!/bin/sh

PKG_MGR="paru"

# Aliases
alias {vim,v,vi}="nvim"

alias {l,lf,r}="tmux new-session 'lfub'"

alias lm="ls -t -1"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias g="git"
alias mount-android="jmtpfs /mnt/android"
alias dus="du -s -h"
alias mktex="cp $HOME/.config/latex-template/template.tex ./"
alias disk-usage="ncdu"
alias sshpi="ssh pi@192.168.1.3"
alias sshfspi="sshfs pi@192.168.1.3:/ /mnt/pi-remote/"
alias pru="paru"
alias sudoedit="doasedit"
alias md2pdf="pandoc -V geometry:margin=1in -o output.pdf $1"
alias fzf-Qi='$PKG_MGR -Qi $( $PKG_MGR -Qi | grep "Name * :" | awk "{print \$3, \$4, \$5}" | fzf )'
alias eva="eva --fix 2"
alias monero-wallet-cli="monero-wallet-cli --daemon-address xmrnode.goodbits.dk:18081"
alias g="git"
alias init-react-js="cp -r /usr/share/init-react-js/* $1"
alias ls="ls -lv --color --group-directories-first $@"
alias ols="ls | awk '{k=0;for(i=0;i<=8;i++)k+=((substr(\$1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(\" %0o \",k);print}'"
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias docker-compose-rebuild="docker-compose up -d --no-deps --build"
