#!/bin/sh

# Aliases
alias {vim,v,vi}="nvim"
alias r="ranger"
  # package fzf
alias yays=fzf-packages.sh
alias lm="ls -t -1"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias g="git"
alias mount-android="jmtpfs /mnt/android"
alias dus="du -s -h"
alias mktex="cp $HOME/.config/latex-template/template.tex ./"
alias disk-usage="ncdu"
